### ISSUE TITLE
Concurrency Backend Calls

### ISSUE THREAD

**Issue by njuettner** [zalando-techmonkeys/howler#7]
Backend calls are triggered by the order of implemented backends right now. 

We should use go routines for our backend calls, cause there's no relation between them. Zmon should be called in concurrent with Baboon.

**Comment by szuecs** [comment]
+1
And the main thread should not care about the return values, to do not use channels to sync!
Make sure shared data is not modified within the goroutine!

**Comment by njuettner** [comment]
This issue has been fixed in PR https://github.com/zalando-techmonkeys/howler/pull/12
